### PR TITLE
Update style of see more button

### PR DESCRIPTION
**Pull request by ProNinoGit120**
Update style of see more button with the outline thin and the caret thick.

### CODE REVIEW

**Comment by binarybottle** [comment]
Screenshot?

**Comment by ProNinoGit120** [comment]
Updated the style of see more button.

**Comment by ProNinoGit120** [comment]
Screen Shot 2020-02-04 at 12 19 30 PM

**Comment by ProNinoGit120** [comment]
Screen Shot 2020-02-04 at 12 22 29 PM

**Pull request closed without merging**
