### PR TITLE
Add description field for choice

### LINKED ISSUE #748: ℹ️Add pop-up tooltip box for choices
As a user, I want to see tooltips on answers that have descriptions so that I understand the question and answer more clearly. 
As an editor, I want to add tooltips to help explain the response options a user has so that the user makes the right choice. 

Description: For radio buttons, the user should be displayed a tooltip if there is a tip associated with that question. If there is not a tooltip associated, then the tooltip question mark should not be displayed. The user will have the ability to click the question mark that opens a textbox with information regarding that set of radio buttons. 

Requirements
- If the tooltip has text, then show the tooltip to the user
- If the tooltip does not have text, then do not show the tooltip 
- When the user clicks outside of the tooltip textbox, the tooltip closes
- This will only be for radio button and checkboxes 

User Journey:
Choices with a description will show a question mark icon
1. The user taps the question mark icon
2. A tooltip that renders markdown pops up with text for the user, and disappears when user taps anywhere outside the tooltip

Implementation with applet schema:
For choices with a description, we can add a `schema:description` key, and the tooltip will render the value of this key.

https://github.com/hotavocado/DBT_diary_card/blob/e9d188f05b96893261c121cdfec6da2006f0e0a6/activities/dbt_daily/items/distress_tolerance#L13-L17

Acceptance Criteria
Given I am a user
When I land on a radio button activity that has descriptions
Then I can click on a tooltip to learn more about the activity 

tooltip

### PR DESCRIPTION
**Pull request by Sshetty2**
Resolves #748

### CODE REVIEW

**Comment by devbtech** [comment]
@Sshetty2 Please resolve conflicts

**Comment by Sshetty2** [comment]
> @Sshetty2 Please resolve conflicts

Resolved

**Comment by devbtech** [comment]
@Sshetty2 Please update project version and changelog. Also which issue does this resolve?

**Comment by devbtech** [comment]
I updated PR description and versions/chagelog

**Review by devbtech — APPROVED** [review]

**Pull request merged**
