### PR TITLE
WIP: Plots

### PR DESCRIPTION
**Pull request by akeshavan**
Simulator Screen Shot - iPhone X - 2019-09-06 at 12 01 54

Renders based on an array of objects with date & key objects, where date is `yyyy-mm-dd` formatted.

### CODE REVIEW

**Comment by akeshavan** [comment]
commit above gives us:

Simulator Screen Shot - iPhone X - 2019-09-06 at 14 02 22

**Comment by binarybottle** [comment]
> Simulator Screen Shot - iPhone X - 2019-09-06 at 12 01 54
> 
> Renders based on an array of objects with date & key objects, where date is `yyyy-mm-dd` formatted.

How exciting to see data come up in the app!  Are the 8 dots supposed to map to the first 8 days in the calendar above (of which 7 days are shown)?

**Comment by binarybottle** [comment]
> commit above gives us:
> 
> Simulator Screen Shot - iPhone X - 2019-09-06 at 14 02 22

Again, excited to see data in the app!  There are 7 dots which must refer to the last 7 days, but only 6 shown (no dot on x = 0)?  Best to have labels on the x-axis to clarify.

[Also, I laughed when I saw the answer to "sleeping aids?" was "Really enjoying things"!]

**Comment by akeshavan** [comment]
Last commit has simple bar chart:

Simulator Screen Shot - iPhone X - 2019-09-06 at 14 27 43

@shnizzedy I think we are ready to connect with the server, but I only really need data from the past 7 days.

**Comment by akeshavan** [comment]
@binarybottle 

> How exciting to see data come up in the app! Are the 8 dots supposed to map to the first 8 days in the calendar above (of which 7 days are shown)?

it was a mistake. this PR is a work in progress, so I'm just documenting progress of each commit, so that someone else can take over if they want to.

> Again, excited to see data in the app! There are 7 dots which must refer to the last 7 days, but only 6 shown (no dot on x = 0)? Best to have labels on the x-axis to clarify.

This isn't real data, I'm just getting ready for when it connects to the server. There are currently 7 dots on the x-axis of all plots. I am aware that there aren't labels on the x-axis, please keep in mind that this is a work in progress.

>  [Also, I laughed when I saw the answer to "sleeping aids?" was "Really enjoying things"!]

The items of this HBN EMA in https://github.com/ReproNim/schema-standardization need to be properly vetted before this goes live.

**Comment by binarybottle** [comment]
I figured as much -- thanks, Anisha!

**Comment by akeshavan** [comment]
@shnizzedy this is ready for review, and can be deployed once  https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/188 is up and working on dev & prod

**Comment by shnizzedy** [comment]
Ooh. I don't think we should deploy to prod until we update the user access stuff and test it. The users on prod have data that could be exposed inappropriately with our current routes.

**Comment by shnizzedy** [comment]
Concern alleviated!

> i did check that it errors out for non-reviewers

I'm building to deploy now, will merge once the build succeeds!

**Comment by akeshavan** [comment]
@shnizzedy ok, I've fixed the tests but since i was testing the iOS-13 branch PR as well, this one now has both!

**Pull request merged**
