### PR TITLE
Feat/improve slider

### PR DESCRIPTION
**Pull request by stufreen**
Swap out the custom Slider component for an open source library. This makes it much less effort to maintain and track down bugs.

The downside (maybe) is that the slider cannot be vertical, only horizontal.

Also fixes a bug which was causing the "logout warning" to not appear if the user tried to log out when they had un-uploaded responses.

image

### CODE REVIEW

**Comment by akeshavan** [comment]
My strong opinion is that an easier to maintain, better working horizontal slider >> poorly functioning, harder to maintain vertical slider.

In the future, we can change this. For now, I'd prefer to merge this PR. @binarybottle thoughts?

**Comment by binarybottle** [comment]
I agree, @akeshavan.  My biggest concern is that non-numeric tick labels will quickly become illegible.

**Comment by akeshavan** [comment]
@binarybottle I think for now we'll have to hide non-numeric ticks. At least until its a dealbreaker for a really important project. I also think radio buttons for non-numeric ticks would be a fine workaround.

**Comment by binarybottle** [comment]
@akeshavan -- So what would a horizontal slider look like?  Would the words and images at either end of the scale go above/below/beside the extreme ends?

**Comment by binarybottle** [comment]
@odziem -- 

To summarize what people have been wanting in a better slider bar, I refer to Stu's backlog (https://github.com/orgs/ChildMindInstitute/projects/9#card-22461241) card:

> React Native app: Improve slider widget (make it smoother, more responsive to touches, and better looking; allow user to tap on vertical line to set knob position) -- make sure that when slider bar goes below the screen that the user can scroll down to see the bottom.

**Comment by shnizzedy** [comment]
> @odziem --
> 
> To summarize what people have been wanting in a better slider bar, I refer to Stu's backlog (https://github.com/orgs/ChildMindInstitute/projects/9#card-22461241) card:
> 
> > React Native app: Improve slider widget (make it smoother, more responsive to touches, and better looking; allow user to tap on vertical line to set knob position) -- make sure that when slider bar goes below the screen that the user can scroll down to see the bottom.

I went ahead and converted [that 看板 card](https://github.com/orgs/ChildMindInstitute/projects/9#card-22461241) to [an issue](https://github.com/ChildMindInstitute/mindlogger-app/issues/300).

**Pull request merged**
