### PR TITLE
Redesign of Progress Bar

### PR DESCRIPTION
**Pull request by Eden2016**

### CODE REVIEW

**Comment by shnizzedy** [comment]
[`GET /context/skin`](https://api.mindlogger.org/api/v1#!/context/context_getSkin) includes a `colors` Object with `primary` and `secondary` values for a given server (although I don't think we have any current routes to add or update colors)

**Comment by binarybottle** [comment]
@Eden2016 -- I preferred the other blue color over this purplish color.  Otherwise it's great!

**Comment by binarybottle** [comment]
> Code looks good. @shnizzedy @binarybottle Do we have an official color scheme documented? This adds a new color, `mediumBlue` to the app. Preview of new progress bar:
> drawing

@Eden2016 had suggested a different blue that I prefer.

**Comment by binarybottle** [comment]
image

**Pull request merged**
