### PR TITLE
Feature/toggle-url

### PR DESCRIPTION
**Pull request by henryrossiter**
Change in authentication to allow api url specification. Url must be specified to sign up or to log in. 

After logging out, url will be pre-populated for next log in (if app is still running).

New log in screen:

image

### CODE REVIEW

**Comment by ccraddock** [comment]
would it be possible to make it so that the url can be populated by reading a qr code? Likewise for the username and password?

**Comment by binarybottle** [comment]
@henryrossiter & @ccraddock -- I understand that entering a url is one way of satisfying your use case, but this should be an optional registration procedure.  Not everyone should have to register this way.  I appreciate the idea of using a qr code, given that urls are long and tedious to type.

**Comment by shnizzedy** [comment]
> would it be possible to make it so that the url can be populated by reading a qr code? Likewise for the username and password?

I like the idea of a QR code, and I agree with @binarybottle that filling that field should be optional, whether by a pre-filled default or extra steps to use that option.

**Comment by henryrossiter** [comment]
Okay, valuable feedback!

A modal on the login/signup page may work well. Pre-populating the url field would also be simple. Adding the qr reader may be a bit trickier.

I'll play with some of these ideas in the next few days.

**Comment by binarybottle** [comment]
That would be great, @henryrossiter!

**Comment by ccraddock** [comment]
How about we do it this way:

- The main signin page would be as before, and not require the user to specify a server url. default behavior would be to go to CMI urls
- at the bottom just about "new user or forgot password?" put a link that is something like "change study", the user could then scan a QR code for the new url, or a text input box

Would this be be a more suitable solution?

**Comment by binarybottle** [comment]
@ccraddock -- I like that solution!

**Comment by henryrossiter** [comment]
@binarybottle @shnizzedy 
Okay, played with @ccraddock 's idea. Thoughts on this?

changeUrl

**Comment by henryrossiter** [comment]
This also affects https://github.com/ChildMindInstitute/mindlogger-app/issues/120

**Pull request merged**
