### PR TITLE
Improve slider

### PR DESCRIPTION
**Pull request by odziem**
This PR is based on https://github.com/ChildMindInstitute/mindlogger-app/pull/227

### CODE REVIEW

**Comment by odziem** [comment]
It is worth noting the open source library leveraged here is no longer maintained. There is a fork with more features here: https://www.npmjs.com/package/@miblanchard/react-native-slider, but there appear to be some bugs with the added functionality. This includes the functionality that allows users to tap on the slider bar to seek to the corresponding value.

Given this, and given that the slider would now be horizontal rather than vertical, I am not convinced of the value of this change. Could it be better to try to improve the old, tested vertical slider instead? Perhaps making it its own library? Or are there other workable slider options? https://github.com/react-native-community/react-native-slider seems to be in active development, although it appears to have some limitations currently as well.

**Comment by binarybottle** [comment]
> There is a fork with more features here: https://www.npmjs.com/package/@miblanchard/react-native-slider, but there appear to be some bugs with the added functionality.

I looked over the issues and didn't see any bugs related to tapping on the slider bar.  They appear to be issues related to differences in appearance between iOS and Android.

**Comment by shnizzedy** [comment]
> I looked over the issues and didn't see any bugs related to tapping on the slider bar. They appear to be issues related to differences in appearance between iOS and Android.

@binarybottle So merge?

**Comment by shnizzedy** [comment]
> So merge?

> Yes

(in person)

**Comment by odziem** [comment]
To clarify:

1. This PR uses the original (unmaintained, but functional) library, which does not have the tapping functionality.
2. The @miblanchard/react-native-slider fork (also not actively maintained) includes the tapping functionality but has a bug where outdated values are returned from `onValueChange` and `onSlidingComplete` events.

**Pull request merged**
