### PR TITLE
0.13.27 - Fix incorrect item ID in order property #1295

### PR DESCRIPTION
**Pull request by ngonzalvez**
Fixex the app crashing when an incorrect item ID is specified
    
The app crashes when an incorrect item ID is included in the reprolib:terms/order property of the schema.
    
Issue #1295

### CODE REVIEW

**Comment by devbtech** [comment]
@ngonzalvez Please update branch is out-of-date with `master`

**Comment by Matchdev120** [comment]
@ngonzalvez It looks like package.json & readme.md is updated yet
Otherwise LGTM!

**Review by Matchdev120 — APPROVED** [review]
LGTM!

**Comment by Matchdev120** [comment]
@devbtech This PR is ready to be merged.

**Pull request merged**
