### PR TITLE
:sparkles: Add applet tabs

### PR DESCRIPTION
**Pull request by devbtech**

### CODE REVIEW

**Comment by devbtech** [comment]
> Two issues I found:
> 
> * when on the 'all' tab is selected, only activities from one applet are shown
> * when I go to another tab, and then back to the 'all' tab, the app navigates back to the `AppletList` screen
> 
> Heres a video of these issues. Notice when I am on the 'all' tab, I only see the activities from the 'Cognitive Task' applet:
> vid

@henryrossiter  I thought it should be. I made changes again. 

What I've changed are
- when "all" tab is selected, all activities are shown
- there's no action like navigating back to "AppletList" when "all" tab is clicked

**Comment by shnizzedy** [comment]
This looks good! Both solutions suggested in https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/63#issuecomment-571246985 are implemented. One curious point: when entering an applet from the applet list, the tabs are not shown, but when entering from "All applets" on the applet list, the tabs are shown. That could be a design choice, but I'd vote against inconsistency and choose one path: always show tabs, never show tabs, have a toggle to show tabs.
benjamin test screengrab

**Comment by devbtech** [comment]
> This looks good! Both solutions suggested in [ChildMindInstitute/MindLogger-bug-reports#63 (comment)](https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/63#issuecomment-571246985) are implemented. One curious point: when entering an applet from the applet list, the tabs are not shown, but when entering from "All applets" on the applet list, the tabs are shown. That could be a design choice, but I'd vote against inconsistency and choose one path: always show tabs, never show tabs, have a toggle to show tabs.
> benjamin test screengrab

@shnizzedy  Thanks for your feedback!  Yeah The tabs should be shown always I think. I will fix that

**Comment by devbtech** [comment]
@shnizzedy I updated the code. It always show tabs now

**Comment by shnizzedy** [comment]
@devbtech "when on the 'all' tab is selected, only activities from one applet are shown" still seems to be an issue:

updated screengrab: all tabs

**Comment by devbtech** [comment]
> @devbtech "when on the 'all' tab is selected, only activities from one applet are shown" still seems to be an issue:
> 
> updated screengrab: all tabs

@shnizzedy  Well It should work. But there is something difference - the whole page (include timeline bar, body, bottom navigation bar) are scrollable. Please scroll down the page and you will see the other applets as well.   

What I worried was if we only show survey data of all applets in the body(between timeline bar and bottom navigation bar), we're not able to handle other properties(Data and About in the bottom navigation bar) when 'all' tab is selected - What should we show on data/about page when 'all' tab is selected? 

So my solution was to make whole page scrollable.
This seems to be not a perfect solution and I feel a bit odd myself though. :)

I believe this's a thing we have to make sure we're on the same page.

**Comment by shnizzedy** [comment]
Oh cool!

scrolling

I think the "all" tab should just not have the tabs at the bottom, but don't worry about changing it for this test submission.

**Pull request closed without merging**
